# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: 
      - main
      - jardin
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .

    - name: Run Docker container
      run: |
        docker run -d --name fastapi-container my-fastapi-app

    - name: Install test dependencies
      run: |
        docker exec fastapi-container pip install pytest pytest-asyncio httpx

    - name: Run tests inside Docker container
      run: |
        docker exec fastapi-container pytest

    - name: Stop and remove Docker container
      run: |
        docker stop fastapi-container
        docker rm fastapi-container
