services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: jardin_anciens
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db/migration.sql:/migration.sql
      - ./app/db/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    command: ["/bin/sh", "-c", "chmod +x /docker-entrypoint-initdb.d/migrate.sh && docker-entrypoint.sh postgres"]

  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
  web_data:
